### ISSUE TITLE
CLI Connection Refused

### ISSUE THREAD

**Issue by AndreAga** [AKSW/RDFUnit#33]
Hi, I'm trying to execute RDFUnit via CLI whit this command:

bin/rdfunit -d /...../Dataset.rdf -o ttl

I get this error:
```
java.lang.RuntimeException: HttpException: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused: Unexpected error making the query: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused
	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:98)
	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.execSelect(QueryExecutionCacheEx.java:210)
	at org.aksw.jena_sparql_api.pagination.core.ResultSetPaginated.prefetch(ResultSetPaginated.java:97)
	at org.aksw.jena_sparql_api.pagination.core.ResultSetPaginated.prefetch(ResultSetPaginated.java:49)
	at org.aksw.commons.collections.PrefetchIterator.preparePrefetch(PrefetchIterator.java:35)
	at org.aksw.commons.collections.PrefetchIterator.getCurrent(PrefetchIterator.java:51)
	at org.aksw.commons.collections.PrefetchIterator.hasNext(PrefetchIterator.java:58)
	at org.aksw.jena_sparql_api.pagination.core.QueryExecutionIterated.execSelect(QueryExecutionIterated.java:92)
	at org.aksw.rdfunit.Utils.RDFUnitUtils.fillSchemaServiceFromLOV(RDFUnitUtils.java:138)
	at org.aksw.rdfunit.validate.cli.ValidateCLI.main(ValidateCLI.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: HttpException: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused: Unexpected error making the query: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:417)
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:358)
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:295)
	at com.hp.hpl.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:346)
	at com.hp.hpl.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:338)
	at org.aksw.jena_sparql_api.core.QueryExecutionDecoratorBase.execSelect(QueryExecutionDecoratorBase.java:75)
	at org.aksw.jena_sparql_api.delay.core.QueryExecutionDelay.execSelect(QueryExecutionDelay.java:33)
	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:76)
	... 15 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:118)
	at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1108)
	at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:385)
	at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:447)
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:346)
	... 21 more
Caused by: java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	... 31 more
[ERROR RDFUnitUtils] Encountered error when reading schema information from LOV, schema prefixes & auto schema discovery might not work as expected
java.lang.RuntimeException: Underlying result set not avaliable - probably a query failed.
	at org.aksw.jena_sparql_api.pagination.core.QueryExecutionIterated.execSelect(QueryExecutionIterated.java:107)
	at org.aksw.rdfunit.Utils.RDFUnitUtils.fillSchemaServiceFromLOV(RDFUnitUtils.java:138)
	at org.aksw.rdfunit.validate.cli.ValidateCLI.main(ValidateCLI.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
[INFO  RDFUnitUtils] Loaded 0 schema declarations from LOV SPARQL Endpoint
[INFO  RDFUnitUtils] Loaded 12 schema declarations from: java.io.FileInputStream@650ebab7
[INFO  ValidateUtils] Searching for used schemata in dataset
[WARN  DatasetStatistics] Undefined namespace in LOV or schemaDecl.csv: http://www.w3.org/1999/02/22-rdf-syntax-ns#
[WARN  DatasetStatistics] Undefined namespace in LOV or schemaDecl.csv: http://linkeddata.comune.fi.it:8080/resource/data/
[WARN  DatasetStatistics] Undefined namespace in LOV or schemaDecl.csv: http://www.w3.org/2000/01/rdf-schema#
[INFO  SimpleTestExecutorMonitor] Testing /Users/AndreAga/Documents/Sviluppo/Progetti/UnifiedViews/Datasets/FirenzeSinistri.rdf
[INFO  SimpleTestExecutorMonitor] Tests run: 0, Failed: 0, Timeout: 0, Error: 0. Individual Errors: 0
[INFO  ValidateCLI] Results stored in: ../data/results/_Users_AndreAga_Documents_Sviluppo_Progetti_UnifiedViews_Datasets_FirenzeSinistri.rdf.aggregatedTestCaseResult.*
```

**Comment by roland-c** [comment]
Hi Andrea,

The service lov.okfn.org is offline, that' s what the error is about.
We need to wait untill it is online again.

Best,
Roland

On 18-03-15 20:38, Andrea Agazzone wrote:
>
> Hi, I'm trying to execute RDFUnit via CLI whit this command:
>
> bin/rdfunit -d /...../Dataset.rdf -o ttl
>
> I get this error:
>
> |java.lang.RuntimeException: HttpException: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused: Unexpected error making the query: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused
>      at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:98)
>      at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.execSelect(QueryExecutionCacheEx.java:210)
>      at org.aksw.jena_sparql_api.pagination.core.ResultSetPaginated.prefetch(ResultSetPaginated.java:97)
>      at org.aksw.jena_sparql_api.pagination.core.ResultSetPaginated.prefetch(ResultSetPaginated.java:49)
>      at org.aksw.commons.collections.PrefetchIterator.preparePrefetch(PrefetchIterator.java:35)
>      at org.aksw.commons.collections.PrefetchIterator.getCurrent(PrefetchIterator.java:51)
>      at org.aksw.commons.collections.PrefetchIterator.hasNext(PrefetchIterator.java:58)
>      at org.aksw.jena_sparql_api.pagination.core.QueryExecutionIterated.execSelect(QueryExecutionIterated.java:92)
>      at org.aksw.rdfunit.Utils.RDFUnitUtils.fillSchemaServiceFromLOV(RDFUnitUtils.java:138)
>      at org.aksw.rdfunit.validate.cli.ValidateCLI.main(ValidateCLI.java:61)
>      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      at java.lang.reflect.Method.invoke(Method.java:497)
>      at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
>      at java.lang.Thread.run(Thread.java:745)
> Caused by: HttpException: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused: Unexpected error making the query: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused
>      at com.hp.hpl.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:417)
>      at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:358)
>      at com.hp.hpl.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:295)
>      at com.hp.hpl.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:346)
>      at com.hp.hpl.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:338)
>      at org.aksw.jena_sparql_api.core.QueryExecutionDecoratorBase.execSelect(QueryExecutionDecoratorBase.java:75)
>      at org.aksw.jena_sparql_api.delay.core.QueryExecutionDelay.execSelect(QueryExecutionDelay.java:33)
>      at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:76)
>      ... 15 more
> Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://helium.okfnlabs.org:3030 refused
>      at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
>      at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
>      at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
>      at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
>      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
>      at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
>      at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:118)
>      at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1108)
>      at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:385)
>      at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:447)
>      at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:346)
>      ... 21 more
> Caused by: java.net.ConnectException: Operation timed out
>      at java.net.PlainSocketImpl.socketConnect(Native Method)
>      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
>      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
>      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
>      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>      at java.net.Socket.connect(Socket.java:589)
>      at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
>      at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
>      ... 31 more
> [ERROR RDFUnitUtils] Encountered error when reading schema information from LOV, schema prefixes & auto schema discovery might not work as expected
> java.lang.RuntimeException: Underlying result set not avaliable - probably a query failed.
>      at org.aksw.jena_sparql_api.pagination.core.QueryExecutionIterated.execSelect(QueryExecutionIterated.java:107)
>      at org.aksw.rdfunit.Utils.RDFUnitUtils.fillSchemaServiceFromLOV(RDFUnitUtils.java:138)
>      at org.aksw.rdfunit.validate.cli.ValidateCLI.main(ValidateCLI.java:61)
>      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      at java.lang.reflect.Method.invoke(Method.java:497)
>      at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
>      at java.lang.Thread.run(Thread.java:745)
> [INFO  RDFUnitUtils] Loaded 0 schema declarations from LOV SPARQL Endpoint
> [INFO  RDFUnitUtils] Loaded 12 schema declarations from: java.io.FileInputStream@650ebab7
> [INFO  ValidateUtils] Searching for used schemata in dataset
> [WARN  DatasetStatistics] Undefined namespace in LOV or schemaDecl.csv: http://www.w3.org/1999/02/22-rdf-syntax-ns#
> [WARN  DatasetStatistics] Undefined namespace in LOV or schemaDecl.csv: http://linkeddata.comune.fi.it:8080/resource/data/
> [WARN  DatasetStatistics] Undefined namespace in LOV or schemaDecl.csv: http://www.w3.org/2000/01/rdf-schema#
> [INFO  SimpleTestExecutorMonitor] Testing /Users/AndreAga/Documents/Sviluppo/Progetti/UnifiedViews/Datasets/FirenzeSinistri.rdf
> [INFO  SimpleTestExecutorMonitor] Tests run: 0, Failed: 0, Timeout: 0, Error: 0. Individual Errors: 0
> [INFO  ValidateCLI] Results stored in: ../data/results/_Users_AndreAga_Documents_Sviluppo_Progetti_UnifiedViews_Datasets_FirenzeSinistri.rdf.aggregatedTestCaseResult.*
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AKSW/RDFUnit/issues/33>.
>

-- 
Signature Metamatter/Roland Cornelissen
metamatter*| *Drs. Roland Cornelissen*| *Weersterweg 12*| *9832TE*| *Den 
Horn*| *T +31 (0)50 5515369*| *M +31 (0)6 14797518*| *www.metamatter.nl 
<http://www.metamatter.nl>

**Comment by AndreAga** [comment]
Hi Roland, thanks. 
Can I know what type of service is? What does it provide?

**Comment by roland-c** [comment]
LOV is Linked Open Vocabularies which is a service maintained by OKFN that provides an api for resolving vocabularies. Sadly enough it is hacked days ago and it is unclear when it will come up again.
