### ISSUE TITLE
HasNoModelException thrown analyzing skos.rdf

### ISSUE THREAD

**Issue by fcbr** [AKSW/RDFUnit#40]
We were getting this error and were able to narrow down to just SKOS, as follows.  Any ideas of what's the issue here?

```
fcbr@FCBR-TP:~/repos/RDFUnit/bin$ java -Xmx5g -jar rdfunit-validate-0.7.7-SNAPSHOT-jar-with-dependencies.jar -d http://www.w3.org/TR/skos-reference/skos.rdf
[INFO  RDFUnitUtils] Loaded 517 additional schema declarations from LOV SPARQL Endpoint
[INFO  RDFUnitUtils] Loaded 14 schema declarations from: java.io.FileInputStream@b7bccb4e
[INFO  ValidateUtils] Searching for used schemata in dataset
[INFO  TestGeneratorExecutor] Generating tests for: http://www.w3.org/2004/02/skos/core#
Exception in thread "main" com.hp.hpl.jena.rdf.model.HasNoModelException: 4ad4b639:14f508389b0:-7ff6
	at com.hp.hpl.jena.rdf.model.impl.ResourceImpl.mustHaveModel(ResourceImpl.java:164)
	at com.hp.hpl.jena.rdf.model.impl.ResourceImpl.addProperty(ResourceImpl.java:277)
	at org.aksw.rdfunit.elements.writers.ResultAnnotationWriter.write(ResultAnnotationWriter.java:70)
	at org.aksw.rdfunit.tests.TestCaseAnnotation.serialize(TestCaseAnnotation.java:85)
	at org.aksw.rdfunit.tests.TestCase.serialize(TestCase.java:77)
	at org.aksw.rdfunit.tests.PatternBasedTestCase.serialize(PatternBasedTestCase.java:54)
	at org.aksw.rdfunit.utils.TestUtils.writeTestsToFile(TestUtils.java:291)
	at org.aksw.rdfunit.tests.generators.TestGeneratorExecutor.generateAutoTestsForSchemaSource(TestGeneratorExecutor.java:149)
	at org.aksw.rdfunit.tests.generators.TestGeneratorExecutor.generateTestSuite(TestGeneratorExecutor.java:106)
	at org.aksw.rdfunit.validate.cli.ValidateCLI.main(ValidateCLI.java:113)
'''

**Comment by jimkont** [comment]
under heavy refactoring atm and introduced a new bug :)
let me know if the commit fixes the problem
